# Generated by Django 5.1.1 on 2024-09-10 21:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='date_de_fabrication',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='product',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productitem',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='statut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monapp.statut'),
        ),
    ]
