# Generated by Django 5.1.1 on 2024-10-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0007_remove_order_products_remove_orders_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
