# Generated by Django 5.1.1 on 2024-10-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0008_remove_order_date_received_remove_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
