# Generated by Django 5.1.1 on 2024-10-17 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0008_productitem_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='supplied_by', to='monapp.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.productitem'),
        ),
    ]
