# Generated by Django 5.1.1 on 2024-10-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0010_remove_product_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(related_name='supplied_products', to='monapp.supplier'),
        ),
    ]
